 # this is good when using the local imeges
services:
  database:
    image: postgres
    ports: 
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=infoDB

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports: 
      - 8080:8080

  backend:
    build:
      context: ./app
    ports:
      - "8000:8000" 
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASS: pass123
      DB_NAME: infoDB
      DB_PORT: "5432"
    depends_on:
      - database 

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend 
